/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf --transform
Author: zizian (https://sketchfab.com/zizian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ferrari-roma-vr-ready-nr-130-no-for-sell-eed82330760041b7bb9583cff3e97813
Title: Ferrari Roma VR Ready nr 1/30 (no for sell)
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { MeshBasicMaterial } from "three"

export function FerrariRoma(props) {
  const { nodes, materials } = useGLTF("/scene-transformed-ferrari-roma.glb")
  return (
    <group {...props} dispose={null}>
      <lineSegments
        geometry={nodes.Material2_5.geometry}
        material={materials.edge_color000255}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2.geometry}
        material={materials.ferrari_roma_black3}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_1.geometry}
        material={materials.ferrari_roma_chrome}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_2.geometry}
        material={materials.ferrari_roma_red}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_3.geometry}
        material={materials.ferrari_roma_yellow}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_4.geometry}
        material={materials.ferrari_roma_green}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_6.geometry}
        material={materials.ferrari_roma_glass_tint}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_7.geometry}
        material={materials.ferrari_roma_display2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_8.geometry}
        material={materials.ferrari_roma_steer_alpha}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_9.geometry}
        material={materials.ferrari_roma_carbon}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material6.geometry}
        material={materials.ferrari_roma_kolonka_3}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material8.geometry}
        material={materials.ferrari_roma_kolonka_5}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_10.geometry}
        material={materials.ferrari_roma_INT_DETAILS_plastic}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_11.geometry}
        material={materials.ferrari_roma_windowglass}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_12.geometry}
        material={materials.ferrari_roma_INT_leather_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_13.geometry}
        material={materials.ferrari_roma_INT_DISPLAY_RPM}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material7.geometry}
        material={materials.ferrari_roma_kolonka_4}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4.geometry}
        material={materials.ferrari_roma_kolonka_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_14.geometry}
        material={materials.ferrari_roma_Material__8}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_15.geometry}
        material={materials.ferrari_roma_kolonka}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3.geometry}
        material={materials.ferrari_roma_kolonka_0}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material5.geometry}
        material={materials.ferrari_roma_kolonka_2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material9.geometry}
        material={materials.ferrari_roma_kolonka_6}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_16.geometry}
        material={materials.ferrari_roma_INT_CM_DASH}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_17.geometry}
        material={materials.ferrari_roma_INT_DISPLAY_COLOR}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_18.geometry}
        material={materials.ferrari_roma_INT_DISPLAY_AT}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_19.geometry}
        material={materials.ferrari_roma_logo}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_20.geometry}
        material={materials.ferrari_roma_interior_o}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_21.geometry}
        material={materials.ferrari_roma_plastic_ext}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_22.geometry}
        material={materials.ferrari_roma_INT_plastic}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_23.geometry}
        material={materials.ferrari_roma_redglass}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_24.geometry}
        material={materials.ferrari_roma_INT_METAL_CHROME}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_25.geometry}
        material={materials.ferrari_roma_BadgeA}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_26.geometry}
        material={materials.ferrari_roma_InteriorTilling}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_27.geometry}
        material={materials.ferrari_roma_clearglass}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_28.geometry}
        material={materials.ferrari_roma_mirror}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_29.geometry}
        material={materials.ferrari_roma_interior2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_30.geometry}
        material={materials.ferrari_roma_INT_speaker}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_1.geometry}
        material={materials.ferrari_roma_clearglass_7}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_31.geometry}
        material={materials.ferrari_roma_interior}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_32.geometry}
        material={materials.ferrari_roma_INT_plastic_matte}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_33.geometry}
        material={materials.ferrari_roma_carpaint}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_34.geometry}
        material={materials.gold1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_35.geometry}
        material={materials.Color_4}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_2.geometry}
        material={materials.Color_002}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_36.geometry}
        material={materials.Color_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_37.geometry}
        material={materials.Color_A11}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_38.geometry}
        material={materials.Chrome}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_39.geometry}
        material={materials.Ferrari_F50_1995_Modified_CSB_CSR2_Badge}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_40.geometry}
        material={materials.Charcoal}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_41.geometry}
        material={materials.Color_008_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_42.geometry}
        material={materials.Color_M08}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_43.geometry}
        material={materials.MT__15_8}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_44.geometry}
        material={materials.MT__15_3}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_45.geometry}
        material={materials.Material__8}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
    </group>
  )
}

useGLTF.preload("/scene-transformed-ferrari-roma.glb")
