/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf --transform
Author: zizian (https://sketchfab.com/zizian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bugatti-divo-vr-ready-139c657dc8034af49fc49ca5591852d7
Title: Bugatti Divo VR Ready
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function Bugatti(props) {
  const { nodes, materials } = useGLTF("/scene-transformed-bugatti.glb")
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Material2.geometry}
        material={materials.Color_M09}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3.geometry}
        material={materials.Color_H05}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_1.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Textured}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Textured_14}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material5.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Textured_16}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material5_1.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Textured_15}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material6.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Textured_18}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material6_1.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Textured_17}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_2.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Calliper_Color}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_1.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_CarPaint}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_2.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_InteriorA_Zone2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_3.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_Zone2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4_1.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_Zone2_19}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material7.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_Zone2_25}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material8.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_Zone2_26}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material5_2.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_Zone2_28}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material5_3.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_Zone2_30}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material14.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_Zone2_29}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material5_4.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_Zone2_22}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4_2.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_Zone2_20}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4_3.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_Zone2_21}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material7_1.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_Zone2_31}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material6_2.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_Zone2_32}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material11.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_Zone2_34}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_4.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_36}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_3.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Badge}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4_4.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_39}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_5.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_38}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_4.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4_5.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_37}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material7_2.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_40}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material6_3.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_41}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material8_1.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_42}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material7_3.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_43}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material10.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_44}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material9.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_45}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4_6.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_46}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material5_5.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_47}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material6_4.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_48}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material8_2.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_49}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4_7.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_51}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material13.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_50}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material10_1.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_52}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material11_1.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_53}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4_8.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Interior_54}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_5.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Grille1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_6.geometry}
        material={materials.Color_M08}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_7.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Coloured}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_8.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_InteriorTilling}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_9.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_Window}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_10.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_GlassRed}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_11.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_GlassClear}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_12.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Light}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_13.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Grille2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_14.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_DefaultMaterial}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_15.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Textured2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_16.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Calliper_Textured}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_17.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Base}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_18.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Wheel1A_Rim}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4_9.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Wheel1A_Rim_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material5_6.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Wheel1A_Rim_2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_6.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Wheel1A_Rim_0}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material6_5.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Wheel1A_Rim_3}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material7_4.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Wheel1A_Rim_4}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_19.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Wheel1A_Tire}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material8_3.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Wheel1A_Rim_5}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material9_1.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Wheel1A_Rim_6}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material10_2.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Wheel1A_Rim_7}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material11_2.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Wheel1A_Rim_8}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material12.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Wheel1A_Rim_10}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material13_1.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_Wheel1A_Rim_11}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_20.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_WindowDark}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_21.geometry}
        material={materials.Bugatti_Divo110_2019_Modified_CSB_CSR2_InteriorA}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
    </group>
  )
}

useGLTF.preload("/scene-transformed-bugatti.glb")
