/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf --transform
Author: zizian (https://sketchfab.com/zizian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ferrari-enzo-vr-ready-8d9640fd0dec4d619e8b0d42e652c5d8
Title: Ferrari Enzo VR Ready
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function FerrariEnzo(props) {
  const { nodes, materials } = useGLTF("/scene-transformed-enzo.glb")
  return (
    <group {...props} dispose={null}>
      <lineSegments
        geometry={nodes.Material2_27.geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2.geometry}
        material={materials.Ferrari_Enzo_plastic}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_1.geometry}
        material={materials.Ferrari_Enzo_badge}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_2.geometry}
        material={materials.Ferrari_Enzo_solid}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_3.geometry}
        material={materials.Ferrari_Enzo_bump_leather}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_4.geometry}
        material={materials.Ferrari_Enzo_leather}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_5.geometry}
        material={materials.Ferrari_Enzo_chrome}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_6.geometry}
        material={materials.Ferrari_Enzo_carbon_fiber}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_7.geometry}
        material={materials.Color_M04}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_8.geometry}
        material={materials.Ferrari_Enzo_digital_gauge}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_9.geometry}
        material={materials.Ferrari_Enzo_metal}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_10.geometry}
        material={materials.Ferrari_Enzo_frame}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_11.geometry}
        material={materials.Ferrari_Enzo_window}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_12.geometry}
        material={materials.Ferrari_Enzo_undercarriage}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_13.geometry}
        material={materials.Ferrari_Enzo_detail_glass_red}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_14.geometry}
        material={materials.Ferrari_Enzo_emblem}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_15.geometry}
        material={materials.Ferrari_Enzo_body}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_16.geometry}
        material={materials.Ferrari_Enzo_grille1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_17.geometry}
        material={materials.Ferrari_Enzo_grille1_alpha}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_18.geometry}
        material={materials.Ferrari_Enzo_black_glass}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_19.geometry}
        material={materials.Ferrari_Enzo_glass}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_20.geometry}
        material={materials.Color_M07_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_21.geometry}
        material={materials.Ferrari_Enzo_misc}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_22.geometry}
        material={materials.Ferrari_Enzo_mirrorMiddle}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_23.geometry}
        material={materials.Ferrari_Enzo_lights_glass}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3.geometry}
        material={materials.Color_M07}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_1.geometry}
        material={materials.Color_M08}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_24.geometry}
        material={materials.Ferrari_Enzo_head_light}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_25.geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_26.geometry}
        material={materials.Color_008}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_2.geometry}
        material={materials.tyre2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4.geometry}
        material={materials.Honeycomb_0}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_3.geometry}
        material={materials.White}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_28.geometry}
        material={materials.Carro_Metal_Vermelho_4}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_4.geometry}
        material={materials.Honeycomb}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_5.geometry}
        material={materials.Carro_Metal_Amarelo_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_29.geometry}
        material={materials.Carro_Freio_Disco}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_30.geometry}
        material={materials.Ferrari_Enzo_mirrorMiddle_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
    </group>
  )
}

useGLTF.preload("/scene-transformed-enzo.glb")
