/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf --transform
Author: zizian (https://sketchfab.com/zizian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bmw-seria-8-vr-ready-0455c95a38cd4e458b80374693b7f68b
Title: BMW seria 8 VR Ready
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function BMW(props) {
  const { nodes, materials } = useGLTF("/scene-transformed-bmw.glb")
  return (
    <group {...props} dispose={null}>
      <lineSegments
        geometry={nodes.Material2_6.geometry}
        material={materials.edge_color109113114255}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2.geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_1.geometry}
        material={materials.Color_C02}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3.geometry}
        material={materials["2021_BMW_M8_Convertible_CSR2_CarPaint"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_1.geometry}
        material={materials.material_3}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_2.geometry}
        material={materials.Color_M09}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_3.geometry}
        material={materials.Color_A07}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_4.geometry}
        material={materials.Color_M02}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_2.geometry}
        material={materials["2021_BMW_M8_Convertible_CSR2_Grille2"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_3.geometry}
        material={materials.Translucent_Glass_Gray}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_4.geometry}
        material={materials["2021_BMW_M8_Convertible_GlassClear"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_5.geometry}
        material={materials["2021_BMW_M8_Convertible_Window"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_5.geometry}
        material={materials.Color_C01}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_7.geometry}
        material={materials["2021_BMW_M8_Convertible_CSR2_InteriorA"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_6.geometry}
        material={materials.Color_I04}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_7.geometry}
        material={materials.Color_I08}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_8.geometry}
        material={materials.BMW_M8_2020_Modified__CSB_interior}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_8.geometry}
        material={materials.Color_F06}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_9.geometry}
        material={materials.Color_B05}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_10.geometry}
        material={materials.Translucent_Glass_Tinted_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_11.geometry}
        material={materials["2021_BMW_M8_Convertible_CSR2_Light"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_12.geometry}
        material={materials.Color_G06}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_13.geometry}
        material={materials.Translucent_Glass_Tinted}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_9.geometry}
        material={materials.tyre1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4.geometry}
        material={materials.Honeycomb_0}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_10.geometry}
        material={materials.Color_008}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_11.geometry}
        material={materials.Honeycomb}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4_1.geometry}
        material={materials.Honeycomb_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_12.geometry}
        material={materials.MT__15_17}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_14.geometry}
        material={materials.material_10}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_13.geometry}
        material={materials.edge_color109113114255}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_15.geometry}
        material={materials.MT__15_16_2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_14.geometry}
        material={materials.MT__15_16}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_15.geometry}
        material={materials.MT__15_15}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_16.geometry}
        material={materials.material_9}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_16.geometry}
        material={materials.MT__15_7}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_17.geometry}
        material={materials.MT__15_15_3}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_17.geometry}
        material={materials.MT__15_14}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_18.geometry}
        material={materials.material_4}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_18.geometry}
        material={materials.MT__16}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_19.geometry}
        material={materials.material_6}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_20.geometry}
        material={materials.MT__15_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_19.geometry}
        material={materials.MT__15_18}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_20.geometry}
        material={materials["2022_Lamborghini_Countach_LPI_800-4_Wheel"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_21.geometry}
        material={materials.MT__15_2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_21.geometry}
        material={materials["2022_Lamborghini_Countach_LPI_800-4_BlackGlossy"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_22.geometry}
        material={materials.MT__15_8}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_22.geometry}
        material={materials.Material__8}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_23.geometry}
        material={materials.MT__15_3}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_24.geometry}
        material={materials.Color_004}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_25.geometry}
        material={materials.MT__15_4}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_26.geometry}
        material={materials.Color_5}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_23.geometry}
        material={materials.Color_4}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_24.geometry}
        material={materials["0136_Charcoal_1"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_27.geometry}
        material={materials.Groundcover_Rock_Crushed_2inch_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_28.geometry}
        material={materials.Color_008_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_25.geometry}
        material={materials.Color_C15}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_29.geometry}
        material={materials.MT__15_1_4}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_30.geometry}
        material={materials.MT__15}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_31.geometry}
        material={materials.Color_A11}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_32.geometry}
        material={materials.MT__15__5}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_26.geometry}
        material={materials.MT__15__6}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_33.geometry}
        material={materials.MT__15_5}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_27.geometry}
        material={materials.MT__15_5_7}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4_2.geometry}
        material={materials.MT__15_5_8}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_28.geometry}
        material={materials.MT__15__9}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material4_3.geometry}
        material={materials.MT__15__10}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material9.geometry}
        material={materials.MT__15__15}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material6.geometry}
        material={materials.MT__15__12}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material5.geometry}
        material={materials.MT__15__11}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material8.geometry}
        material={materials.MT__15__14}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material7.geometry}
        material={materials.MT__15__13}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_34.geometry}
        material={materials.Asphalt_New_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_35.geometry}
        material={materials.MT__15_6}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_29.geometry}
        material={materials.Color_A16}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_36.geometry}
        material={materials.MT__15_21}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material2_37.geometry}
        material={materials.material_1}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_30.geometry}
        material={materials.MT__15_12}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_31.geometry}
        material={materials.Metal_Rough_2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
      <mesh
        geometry={nodes.Material3_32.geometry}
        material={materials.MT__15_5_17}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.024}
      />
    </group>
  )
}

useGLTF.preload("/scene-transformed-bmw.glb")
