/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf --transform
Author: zizian (https://sketchfab.com/zizian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/murcielago-tuning-hq-interior-2-c07688aa01ee46458ef36b2b3d249797
Title: Murcielago Tuning HQ Interior (2)
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function Murcielago(props) {
  const { nodes, materials } = useGLTF("/scene-transformed-murcielago.glb")
  return (
    <group {...props} dispose={null}>
      <lineSegments
        geometry={nodes.Material2_6.geometry}
        material={materials.LP_640_plastic_0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2.geometry}
        material={materials.LP_640_lights_glass}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_1.geometry}
        material={materials.Color_A01}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_2.geometry}
        material={materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_3.geometry}
        material={materials.LP_640_window}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material3.geometry}
        material={materials.material_4}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material3_1.geometry}
        material={materials.LP_640_body}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_4.geometry}
        material={materials.Color_M02}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_5.geometry}
        material={materials.LP_640_plastic}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material3_2.geometry}
        material={materials.LP_640_plastic_0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material3_3.geometry}
        material={materials.Color_A08_6}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material3_4.geometry}
        material={materials.Translucent_Glass_Tinted}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material3_5.geometry}
        material={materials.Color_C05}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material3_6.geometry}
        material={materials.Translucent_Glass_Tinted_1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material3_7.geometry}
        material={materials.Color_B04}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material3_8.geometry}
        material={materials.Color_E04}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Material2_7.geometry}
        material={materials.Color_M08}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload("/scene-transformed-murcielago.glb")
